// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thjmjegnbkpdeekghesh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoam1qZWduYmtwZGVla2doZXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1NjM0OTUsImV4cCI6MjEwNjEzOTQ5NX0.XRkbc64R0HMPnwdnfDBYp0JWbrSItbNT5_dX4I78UkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});